import {
	API_VERSION_EXEC,
	API_VERSION_EVENT,
	API_NEW_VERSION_EVENT,
	API40_VERSION_EXEC,
	API40_VERSION_EVENT,
	Version
} from "./Version";
import { IVersion } from "./IVersion";

export { API_VERSION_EXEC, API_VERSION_EVENT, API_NEW_VERSION_EVENT, API40_VERSION_EXEC, API40_VERSION_EVENT, Version };
export type { IVersion };
